export const auditActions = [
  "user:upvoted:post",
  "user:upvoted:comment",
  "user:downvoted:post",
  "user:downvoted:comment",
  "user:deleted:vote:on:comment",
  "user:deleted:vote:on:post",
  "user:switched:vote:on:comment",
  "user:switched:vote:on:post",
  "user:created:post",
  "user:updated:post",
  "user:created:comment",
  "user:updated:comment",
  "user:deleted:post",
  "user:deleted:comment",
  "user:reported:content",
  "user:accepted:terms",
  "user:initialized:account",
  "user:created:account",
  "auth:otp:verify:success",
  "auth:otp:verify:failed",
  "auth:otp:send",
  "user:logged:in:self",
  "user:logged:out:self",
  "user:created:feedback",
  "user:updated:feedback",
  "user:deleted:feedback",
  "user:forgot:password",
  "user:initialized:forgot-password",

  "admin:banned:user",
  "admin:unbanned:user",
  "admin:suspended:user",
  "admin:created:college",
  "admin:deleted:college",
  "admin:updated:college",
  "admin:blocked:content",
  "admin:unblocked:content",
  "admin:shadow:banned:content",
  "admin:shadow:unbanned:content",
  "admin:updated:content",
  "admin:deleted:report",
  "admin:bulk-deleted:reports",
  "admin:updated:report:status",
  "admin:updated:feedback:status",
  "admin:deleted:feedback",

  "system:created:admin:account",
  "admin:logged:out:self",
  "admin:initialized:account",
  "admin:verified:otp",
  "admin:removed:authorized:device",
  "admin:reset:email:otp",
  "admin:deleted:admin:account",
  "admin:updated:admin:account",
  "admin:fetched:all:admin:accounts",

  "system:logged:error",
  "system:logged:in",
  "system:logged:out",

  "other:action",
] as const

export type AuditAction = typeof auditActions[number]
