import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
	PORT: z.coerce.number().default(8000),
	HOST: z.string().default("localhost"),
	NODE_ENV: z.enum(["development", "production", "test"]),
	HTTP_SECURE_OPTION: z.string(),
	ACCESS_CONTROL_ORIGINS: z.string().transform((value) => value.split(",")),
	COOKIE_DOMAIN: z.string(),
	DATABASE_URL: z.string(),
	REDIS_URL: z.string(),
	CACHE_DRIVER: z.enum(["memory", "multi", "redis"]),
	CACHE_TTL: z.coerce.number().default(60),
	ACCESS_TOKEN_TTL: z.string(),
	REFRESH_TOKEN_TTL: z.string(),
	ACCESS_TOKEN_SECRET: z.string().min(32),
	REFRESH_TOKEN_SECRET: z.string().min(32),
	GOOGLE_OAUTH_CLIENT_ID: z.string(),
	GOOGLE_OAUTH_CLIENT_SECRET: z.string(),
	GMAIL_APP_USER: z.string(),
	GMAIL_APP_PASS: z.string(),
	MAILTRAP_TOKEN: z.string(),
	MAIL_PROVIDER: z.enum(["gmail", "resend", "mailtrap"]),
	SERVER_BASE_URI: z.string(),
	PERSPECTIVE_API_KEY: z.string(),
	MAIL_FROM: z.string(),
	EMAIL_ENCRYPTION_KEY: z.string().min(32),
	EMAIL_SECRET: z.string().min(32),
	HMAC_SECRET: z.string().min(32),
	ADMIN_EMAIL: z.email(),
	ADMIN_PASSWORD: z.string().min(8),
	BETTER_AUTH_URL: z.string(),
	BETTER_AUTH_SECRET: z.string(),
	CLOUDINARY_CLOUD_NAME: z.string().optional(),
	CLOUDINARY_API_KEY: z.string().optional(),
	CLOUDINARY_API_SECRET: z.string().optional(),
	CLOUDINARY_UPLOAD_FOLDER: z.string().optional().default("flick/colleges"),
});

export const env = envSchema.parse(process.env);
